format: 0.2.0
name: subgraph-query
validation: ./validator.cue
jobs:
  cases:
    steps:
    - uri: fs/build
      method: subgraphQuery
      args:
        subgraphAuthor: ensdomains
        subgraphName: ens
        query: "{\ndomains(first: 5) {\nid\nname\nlabelName\nlabelhash\n}\n}"
